### PR TITLE
Use "box" input for time inputs

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
I created this from github.dev, sorry the PR description doesn't explain why I'm making this change.

I had a problem when I wanted to try editing 'hotwater_runtime_m'. The slider input creates a slider between 0 and 32767, and it's impossible to set a specific wanted value. All of the 'time_input' registers have this range, so the problem will apply to all of them.

**Comment by foolip** [comment]
Given the dependency of the Lovelace component on Number Box and that the description of that is "Replace input_number sliders with plus and minus buttons" I think there's a risk that breaks that component.

I never got that component working (even after https://github.com/ThermIQ/thermiq_mqtt-ha/commit/337317f84848bd681007997a04cbc139c08dd612) so I've made my own list of inputs from the entities directly. That's why I'm seeing the slider. I don't know if this change breaks the custom component.

**Comment by foolip** [comment]
I actually got the custom component working today, but I still think this would be an improvement since one still sees the slider if one clicks on an entity to show details/history.

**Comment by ThermIQ** [comment]
The number box allows for changing the value by + and -. When clicking on name a pop-up appears with an inputbox and graph etc. This is a good enough solution

**Comment by foolip** [comment]
If clicking the name showed a regular input box I would agree there's no problem. However, here's what that popup looks currently for "Hotwater operating time" with the code from https://github.com/ThermIQ/thermiq_mqtt-ha/commit/c04f47c2313c9cb6a210fc61bada619aee537cc8 (forked repo due to installation troubles):
image

That slider can't really be used to set a value, so the only way to change it is one step at a time, which is pretty tedious.

Always using a regular input box simplifies the code and avoids this problem. (As mentioned, I'm not sure if there are other things that regress though.)

**Comment by ThermIQ** [comment]
Got it. Will update to class all inputs as box. Definitely makes more sense together with the number-box

**Comment by ThermIQ** [comment]
Solved in v1.3.2

**Pull request closed without merging**
